version: '2.2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    mem_limit: 1G
    links:
      - "php"
      - "elasticsearch"
      - rabbitmq
    volumes:
      - ../../var/log/nginx:/var/log/nginx
      - ./../config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
      - ./../config/ssl/cert.key:/etc/nginx/ssl/cert.key
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled/:/etc/nginx/conf.d
      - ./../config/nginx/includes:/etc/nginx/includes
    volumes_from:
      - php
  php:
      build:
        context: docker-images
        args:
          USERNAME: ${CONTAINER_USER}
      container_name: php
      volumes:
        - ${DIRECTORY_PROJECTS}:/var/www/html
        - ~/.ssh/:/home/${CONTAINER_USER}/.ssh
        - ~/.magento-cloud/:/home/${CONTAINER_USER}/.magento-cloud
        - ../../.composer56/:/home/${CONTAINER_USER}/.composer
        - ../../tmp/:/tmp
      links:
        - mysql
        - redis
        - elasticsearch
        - rabbitmq
      mem_limit: 1G
      environment:
        - PHP_IDE_CONFIG=serverName=XDebug #use to debug from cli inside docker container call php -dxdebug.remote_host=172.17.0.1 //host IP
      stdin_open: true
      tty: true
  elasticsearch:
      image: elasticsearch:7.13.2
      container_name: elasticsearch
      mem_limit: 1G
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - discovery.type=single-node
  mysql:
    image: mysql:5.7
    container_name: mysql
    mem_limit: 1G
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../../databases/mysql57:/var/lib/mysql
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    mem_limit: 1G
    ports:
      - "1025:1025"
      - "8025:8025"
  redis:
    image: redis:4.0
    container_name: redis
    mem_limit: 1G
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672